"""empty message

Revision ID: 013553e88b97
Revises: 55a7992a03a7
Create Date: 2025-08-20 16:55:44.150339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013553e88b97'
down_revision = '55a7992a03a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
