"""Adicionado coluna tipo em Filme

Revision ID: 55a7992a03a7
Revises: 73d63d0d7eee
Create Date: 2025-08-20 16:54:10.806123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a7992a03a7'
down_revision = '73d63d0d7eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
