"""empty message

Revision ID: 62d9dec1839b
Revises: c8375daec304
Create Date: 2025-08-22 00:27:31.687551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d9dec1839b'
down_revision = 'c8375daec304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_filme')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_filme',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=False),
    sa.Column('temporada', sa.INTEGER(), nullable=True),
    sa.Column('trailer', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=10), nullable=False),
    sa.Column('data_lancamento', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
