"""empty message

Revision ID: 73d63d0d7eee
Revises: 78654a41f2c4
Create Date: 2025-08-20 16:15:01.692058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d63d0d7eee'
down_revision = '78654a41f2c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avaliacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avaliacao', schema=None) as batch_op:
        batch_op.drop_column('comentario')

    # ### end Alembic commands ###
