"""empty message

Revision ID: 78654a41f2c4
Revises: ff5565d90c84
Create Date: 2025-08-18 05:45:10.929734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78654a41f2c4'
down_revision = 'ff5565d90c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_ator_fav')

    op.create_table(
        'usuario_ator_fav',
        sa.Column('usuario_id', sa.Integer, sa.ForeignKey('usuario.id'), primary_key=True),
        sa.Column('ator_id', sa.Integer, sa.ForeignKey('ator.id'), primary_key=True)
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'usuario_ator_fav',
        sa.Column('usuario_id', sa.Integer, sa.ForeignKey('usuario.id'), primary_key=True),
        sa.Column('ator_id', sa.Integer, sa.ForeignKey('filme.id'), primary_key=True)  # a versão errada antiga
    )

    # ### end Alembic commands ###
