"""empty message

Revision ID: 94930120bf32
Revises: d24c3bff69ca
Create Date: 2025-08-23 23:35:19.280863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94930120bf32'
down_revision = 'd24c3bff69ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lancamento', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.drop_column('lancamento')

    # ### end Alembic commands ###
