"""empty message

Revision ID: c8375daec304
Revises: fda2459db4df
Create Date: 2025-08-20 20:17:50.574263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8375daec304'
down_revision = 'fda2459db4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_filme_assistindo')
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_lancamento', sa.Date(), nullable=True))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.drop_column('data_lancamento')

    op.create_table('usuario_filme_assistindo',
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('filme_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['filme_id'], ['filme.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'filme_id')
    )
    # ### end Alembic commands ###
