"""empty message

Revision ID: d24c3bff69ca
Revises: e29908a65fea
Create Date: 2025-08-22 00:34:03.141240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24c3bff69ca'
down_revision = 'e29908a65fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacao')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacao',
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('episodio_id', sa.INTEGER(), nullable=False),
    sa.Column('nota', sa.FLOAT(), nullable=False),
    sa.Column('comentario', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['episodio_id'], ['episodio.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'episodio_id')
    )
    # ### end Alembic commands ###
