"""empty message

Revision ID: e29908a65fea
Revises: 62d9dec1839b
Create Date: 2025-08-22 00:32:11.197784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29908a65fea'
down_revision = '62d9dec1839b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.drop_column('ano')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ano', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
