"""empty message

Revision ID: fda2459db4df
Revises: 013553e88b97
Create Date: 2025-08-20 16:57:31.769810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda2459db4df'
down_revision = '013553e88b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.alter_column('temporada',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filme', schema=None) as batch_op:
        batch_op.alter_column('temporada',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
